services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Strong@Passw0rd
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/mssql
    networks:
      - app-network

  migrator:
    build:
      context: .
      dockerfile: Dockerfile.Migrator
    depends_on:
      - sqlserver
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=OrderManagement;User Id=sa;Password=Strong@Passw0rd;TrustServerCertificate=True;MultipleActiveResultSets=true
    networks:
      - app-network

  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - migrator
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=OrderManagement;User Id=sa;Password=Strong@Passw0rd;TrustServerCertificate=True;MultipleActiveResultSets=true
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  sql-data:
